/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.professor;

import control.connection.dataAccess.AlunoAccess;
import control.connection.dataAccess.ChamadaAccess;
import control.connection.dataAccess.PresencaAccess;
import control.connection.dataAccess.TurmasAccess;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import model.Chamada;
import model.PreencheTabela;
import model.Presenca;
import model.Professor;
import javax.swing.JOptionPane;

/**
 *
 * @author benedito
 */
public class Chamadas extends javax.swing.JFrame {

    static ChamadaAccess chamadaAc;
    static Chamada chamada;
    static Professor professor; 
    static Presenca presenca;
    static PresencaAccess presencaAc;
    static AlunoAccess alunoAc;
    static MenuProfessor menu;
    static TurmasAccess turmasAc;
    
    public Chamadas(Professor professor) {
        
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.professor = professor;
        
        jpnChamada.setVisible(false);
        pnMenu.setVisible(false);
        btnSalvar.setVisible(false);
        pnPesq.setVisible(false);
        pnPesquisar.setVisible(false);
        jPanel1.setVisible(false);
        turmasAc = new TurmasAccess();
        for(String turma:turmasAc.lista())
        {
            jcbTurmas.addItem(turma);
        }  
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnVoltar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnVoltar1 = new javax.swing.JButton();
        pnMenuPr = new javax.swing.JPanel();
        btnPesquisar = new javax.swing.JButton();
        btnNova = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        pnPesquisar = new javax.swing.JPanel();
        lblDataAula1 = new javax.swing.JLabel();
        jftDataAulaPesq = new javax.swing.JFormattedTextField();
        jsDataAula1 = new javax.swing.JSeparator();
        lblTurma1 = new javax.swing.JLabel();
        jcbTurmasPesq = new javax.swing.JComboBox<>();
        btnChamadaPesq = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        pnMenu = new javax.swing.JPanel();
        lblDataAula2 = new javax.swing.JLabel();
        jftHorarioAUla = new javax.swing.JFormattedTextField();
        jsDataAula2 = new javax.swing.JSeparator();
        lblDataAula = new javax.swing.JLabel();
        jftDataAula = new javax.swing.JFormattedTextField();
        jsDataAula = new javax.swing.JSeparator();
        lblTurma = new javax.swing.JLabel();
        jcbTurmas = new javax.swing.JComboBox<>();
        btnSalvar = new javax.swing.JButton();
        btnChamada = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jpnJanela = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jpnConteudo = new javax.swing.JPanel();
        jpnEspera = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnPesq = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtChamadasPesq = new javax.swing.JTable();
        jpnChamada = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtChamadas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1178, 730));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);

        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/back-left-arrow-square-button-outline.png"))); // NOI18N
        btnVoltar.setToolTipText("Voltar a Área de Trabalho");
        btnVoltar.setBorder(null);
        btnVoltar.setBorderPainted(false);
        btnVoltar.setContentAreaFilled(false);
        btnVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 60, 60);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setOpaque(false);

        btnVoltar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/back-left-arrow-square-button-outline.png"))); // NOI18N
        btnVoltar1.setToolTipText("Voltar a Área de Trabalho");
        btnVoltar1.setBorder(null);
        btnVoltar1.setBorderPainted(false);
        btnVoltar1.setContentAreaFilled(false);
        btnVoltar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVoltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVoltar1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVoltar1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 10, 60, 60);

        pnMenuPr.setBackground(new java.awt.Color(255, 255, 255));
        pnMenuPr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        pnMenuPr.setLayout(null);

        btnPesquisar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisar.setText("Pesquisar Chamada");
        btnPesquisar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnPesquisar.setContentAreaFilled(false);
        btnPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        pnMenuPr.add(btnPesquisar);
        btnPesquisar.setBounds(30, 370, 220, 40);

        btnNova.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnNova.setForeground(new java.awt.Color(255, 255, 255));
        btnNova.setText("Nova Chamada");
        btnNova.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnNova.setContentAreaFilled(false);
        btnNova.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaActionPerformed(evt);
            }
        });
        pnMenuPr.add(btnNova);
        btnNova.setBounds(30, 310, 220, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/bg-img.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        pnMenuPr.add(jLabel5);
        jLabel5.setBounds(0, 0, 290, 730);

        getContentPane().add(pnMenuPr);
        pnMenuPr.setBounds(0, 0, 290, 730);

        pnPesquisar.setBackground(new java.awt.Color(255, 255, 255));
        pnPesquisar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        pnPesquisar.setLayout(null);

        lblDataAula1.setBackground(new java.awt.Color(27, 144, 240));
        lblDataAula1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblDataAula1.setForeground(new java.awt.Color(255, 255, 255));
        lblDataAula1.setText("Data da aula");
        pnPesquisar.add(lblDataAula1);
        lblDataAula1.setBounds(30, 200, 220, 30);

        jftDataAulaPesq.setBorder(null);
        jftDataAulaPesq.setForeground(new java.awt.Color(153, 153, 153));
        try {
            jftDataAulaPesq.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftDataAulaPesq.setText("00/00/0000");
        jftDataAulaPesq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jftDataAulaPesqMouseClicked(evt);
            }
        });
        jftDataAulaPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftDataAulaPesqActionPerformed(evt);
            }
        });
        pnPesquisar.add(jftDataAulaPesq);
        jftDataAulaPesq.setBounds(30, 230, 220, 30);

        jsDataAula1.setBackground(new java.awt.Color(102, 102, 102));
        jsDataAula1.setForeground(new java.awt.Color(255, 255, 255));
        pnPesquisar.add(jsDataAula1);
        jsDataAula1.setBounds(30, 260, 220, 30);

        lblTurma1.setBackground(new java.awt.Color(27, 144, 240));
        lblTurma1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblTurma1.setForeground(new java.awt.Color(255, 255, 255));
        lblTurma1.setText("Selecionar Turma");
        pnPesquisar.add(lblTurma1);
        lblTurma1.setBounds(30, 290, 220, 30);

        pnPesquisar.add(jcbTurmasPesq);
        jcbTurmasPesq.setBounds(30, 330, 220, 30);

        btnChamadaPesq.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnChamadaPesq.setForeground(new java.awt.Color(255, 255, 255));
        btnChamadaPesq.setText("Carregar chamada");
        btnChamadaPesq.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnChamadaPesq.setContentAreaFilled(false);
        btnChamadaPesq.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChamadaPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChamadaPesqActionPerformed(evt);
            }
        });
        pnPesquisar.add(btnChamadaPesq);
        btnChamadaPesq.setBounds(30, 400, 220, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/bg-img.jpg"))); // NOI18N
        jLabel6.setText("jLabel5");
        pnPesquisar.add(jLabel6);
        jLabel6.setBounds(0, 0, 290, 730);

        getContentPane().add(pnPesquisar);
        pnPesquisar.setBounds(0, 0, 290, 730);

        pnMenu.setBackground(new java.awt.Color(255, 255, 255));
        pnMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        pnMenu.setLayout(null);

        lblDataAula2.setBackground(new java.awt.Color(27, 144, 240));
        lblDataAula2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblDataAula2.setForeground(new java.awt.Color(255, 255, 255));
        lblDataAula2.setText("Horário de Início");
        pnMenu.add(lblDataAula2);
        lblDataAula2.setBounds(30, 240, 220, 30);

        jftHorarioAUla.setBorder(null);
        jftHorarioAUla.setForeground(new java.awt.Color(153, 153, 153));
        try {
            jftHorarioAUla.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftHorarioAUla.setText("00:00");
        jftHorarioAUla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jftHorarioAUlaMouseClicked(evt);
            }
        });
        jftHorarioAUla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftHorarioAUlaActionPerformed(evt);
            }
        });
        pnMenu.add(jftHorarioAUla);
        jftHorarioAUla.setBounds(30, 270, 220, 30);

        jsDataAula2.setBackground(new java.awt.Color(102, 102, 102));
        jsDataAula2.setForeground(new java.awt.Color(255, 255, 255));
        pnMenu.add(jsDataAula2);
        jsDataAula2.setBounds(30, 300, 220, 30);

        lblDataAula.setBackground(new java.awt.Color(27, 144, 240));
        lblDataAula.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblDataAula.setForeground(new java.awt.Color(255, 255, 255));
        lblDataAula.setText("Data da aula");
        pnMenu.add(lblDataAula);
        lblDataAula.setBounds(30, 150, 220, 30);

        jftDataAula.setBorder(null);
        jftDataAula.setForeground(new java.awt.Color(153, 153, 153));
        try {
            jftDataAula.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftDataAula.setText("00/00/0000");
        jftDataAula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jftDataAulaMouseClicked(evt);
            }
        });
        jftDataAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftDataAulaActionPerformed(evt);
            }
        });
        pnMenu.add(jftDataAula);
        jftDataAula.setBounds(30, 180, 220, 30);

        jsDataAula.setBackground(new java.awt.Color(102, 102, 102));
        jsDataAula.setForeground(new java.awt.Color(255, 255, 255));
        pnMenu.add(jsDataAula);
        jsDataAula.setBounds(30, 210, 220, 30);

        lblTurma.setBackground(new java.awt.Color(27, 144, 240));
        lblTurma.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblTurma.setForeground(new java.awt.Color(255, 255, 255));
        lblTurma.setText("Selecionar Turma");
        pnMenu.add(lblTurma);
        lblTurma.setBounds(30, 320, 220, 30);

        pnMenu.add(jcbTurmas);
        jcbTurmas.setBounds(30, 360, 220, 30);

        btnSalvar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("  Salvar");
        btnSalvar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnSalvar.setContentAreaFilled(false);
        btnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        pnMenu.add(btnSalvar);
        btnSalvar.setBounds(30, 490, 220, 40);

        btnChamada.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnChamada.setForeground(new java.awt.Color(255, 255, 255));
        btnChamada.setText("Carregar chamada");
        btnChamada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnChamada.setContentAreaFilled(false);
        btnChamada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChamada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChamadaActionPerformed(evt);
            }
        });
        pnMenu.add(btnChamada);
        btnChamada.setBounds(30, 430, 220, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/bg-img.jpg"))); // NOI18N
        jLabel7.setText("jLabel5");
        pnMenu.add(jLabel7);
        jLabel7.setBounds(0, 0, 290, 730);

        getContentPane().add(pnMenu);
        pnMenu.setBounds(0, 0, 290, 730);

        jpnJanela.setBackground(new java.awt.Color(255, 255, 255));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/minimize.png"))); // NOI18N
        jButton2.setToolTipText("Minimizar o programa");
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/cross-square-button.png"))); // NOI18N
        btnClose.setToolTipText("Fechar o programa");
        btnClose.setBorder(null);
        btnClose.setContentAreaFilled(false);
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnJanelaLayout = new javax.swing.GroupLayout(jpnJanela);
        jpnJanela.setLayout(jpnJanelaLayout);
        jpnJanelaLayout.setHorizontalGroup(
            jpnJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnJanelaLayout.createSequentialGroup()
                .addContainerGap(779, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose)
                .addGap(39, 39, 39))
        );
        jpnJanelaLayout.setVerticalGroup(
            jpnJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jpnJanelaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        getContentPane().add(jpnJanela);
        jpnJanela.setBounds(290, 0, 890, 50);

        jpnConteudo.setBackground(new java.awt.Color(255, 255, 255));
        jpnConteudo.setLayout(null);

        jpnEspera.setBackground(new java.awt.Color(255, 255, 255));
        jpnEspera.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/education.png"))); // NOI18N
        jpnEspera.add(jLabel1);
        jLabel1.setBounds(250, 50, 143, 138);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PARA REALIZAR OU VISUALIZAR UMA CHAMADA PREENCHA ");
        jpnEspera.add(jLabel2);
        jLabel2.setBounds(120, 200, 420, 57);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("OS DADOS AO LADO E PRESSIONE \"CARREGAR CHAMADA\"");
        jpnEspera.add(jLabel3);
        jLabel3.setBounds(130, 260, 430, 19);

        jpnConteudo.add(jpnEspera);
        jpnEspera.setBounds(150, 140, 610, 330);

        pnPesq.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);
        jScrollPane2.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jScrollPane2.setOpaque(false);
        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        jtChamadasPesq.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jtChamadasPesq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Horario", "Turma"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtChamadasPesq.setGridColor(new java.awt.Color(255, 255, 255));
        jtChamadasPesq.setIntercellSpacing(new java.awt.Dimension(3, 3));
        jtChamadasPesq.setOpaque(false);
        jtChamadasPesq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtChamadasPesqMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtChamadasPesq);
        if (jtChamadasPesq.getColumnModel().getColumnCount() > 0) {
            jtChamadasPesq.getColumnModel().getColumn(0).setResizable(false);
            jtChamadasPesq.getColumnModel().getColumn(0).setPreferredWidth(50);
            jtChamadasPesq.getColumnModel().getColumn(1).setResizable(false);
            jtChamadasPesq.getColumnModel().getColumn(2).setResizable(false);
            jtChamadasPesq.getColumnModel().getColumn(2).setPreferredWidth(50);
        }

        javax.swing.GroupLayout pnPesqLayout = new javax.swing.GroupLayout(pnPesq);
        pnPesq.setLayout(pnPesqLayout);
        pnPesqLayout.setHorizontalGroup(
            pnPesqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPesqLayout.createSequentialGroup()
                .addContainerGap(231, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(251, 251, 251))
        );
        pnPesqLayout.setVerticalGroup(
            pnPesqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );

        jpnConteudo.add(pnPesq);
        pnPesq.setBounds(0, 0, 890, 680);

        jpnChamada.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setOpaque(false);

        jtChamadas.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jtChamadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RA", "Nome do Aluno", "Presença"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtChamadas.setGridColor(new java.awt.Color(255, 255, 255));
        jtChamadas.setIntercellSpacing(new java.awt.Dimension(3, 3));
        jtChamadas.setOpaque(false);
        jScrollPane1.setViewportView(jtChamadas);
        if (jtChamadas.getColumnModel().getColumnCount() > 0) {
            jtChamadas.getColumnModel().getColumn(0).setPreferredWidth(70);
            jtChamadas.getColumnModel().getColumn(0).setMaxWidth(70);
            jtChamadas.getColumnModel().getColumn(1).setResizable(false);
            jtChamadas.getColumnModel().getColumn(2).setResizable(false);
            jtChamadas.getColumnModel().getColumn(2).setPreferredWidth(50);
        }

        javax.swing.GroupLayout jpnChamadaLayout = new javax.swing.GroupLayout(jpnChamada);
        jpnChamada.setLayout(jpnChamadaLayout);
        jpnChamadaLayout.setHorizontalGroup(
            jpnChamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnChamadaLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE))
        );
        jpnChamadaLayout.setVerticalGroup(
            jpnChamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );

        jpnConteudo.add(jpnChamada);
        jpnChamada.setBounds(0, 0, 890, 680);

        getContentPane().add(jpnConteudo);
        jpnConteudo.setBounds(290, 50, 890, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jftDataAulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jftDataAulaMouseClicked
        this.jftDataAula.setText("");
    }//GEN-LAST:event_jftDataAulaMouseClicked

    private void jftDataAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftDataAulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftDataAulaActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel)jtChamadas.getModel();
        presencaAc = new PresencaAccess();
        presenca = new Presenca();
        alunoAc = new AlunoAccess();
        for(int i=0;i<modelo.getRowCount();i++)
        {
            presenca.setIdAluno(alunoAc.pegaId((String) modelo.getValueAt(i,0)));
            
            presenca.setIdChamada(chamada.getId());
            
            if((Boolean)modelo.getValueAt(i, 2)==true)
                presenca.setSituacao(1);
            else
                presenca.setSituacao(0);
            
            presencaAc.create(presenca);
        }
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        turmasAc = new TurmasAccess();
        for(String turma:turmasAc.lista())
        {
            jcbTurmasPesq.addItem(turma);
        }  
        pnPesquisar.setVisible(true);
        pnMenuPr.setVisible(false);
        jPanel2.setVisible(false);
        jPanel1.setVisible(true);
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnNovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaActionPerformed
        pnMenuPr.setVisible(false);
        pnMenu.setVisible(true);
        jPanel2.setVisible(false);
        jPanel1.setVisible(true);
        
    }//GEN-LAST:event_btnNovaActionPerformed

    private void btnChamadaPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChamadaPesqActionPerformed
        PreencheTabela preenche2 = new PreencheTabela(jtChamadasPesq,professor.getIdProfessor(),jftDataAulaPesq.getText(),jcbTurmasPesq.getSelectedIndex()+1);
        
        pnPesq.setVisible(true);
        jpnChamada.setVisible(false);
        jpnEspera.setVisible(false);
        
              
        
    }//GEN-LAST:event_btnChamadaPesqActionPerformed

    private void jftDataAulaPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftDataAulaPesqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftDataAulaPesqActionPerformed

    private void jftDataAulaPesqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jftDataAulaPesqMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jftDataAulaPesqMouseClicked

    private void btnChamadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChamadaActionPerformed
        PreencheTabela preenche = new PreencheTabela(jtChamadas,jcbTurmas.getSelectedIndex()+1);
        
        jpnEspera.setVisible(false);
        jpnChamada.setVisible(true);
        btnSalvar.setVisible(true);
        
        chamada = new Chamada();
        chamada.setData(jftDataAula.getText());
        chamada.setIdClasse(jcbTurmas.getSelectedIndex()+1);
        chamada.setIdDisciplina(professor.getMateria());              
        chamada.setIdProfessor(professor.getIdProfessor());
        chamada.setHorario(jftHorarioAUla.getText());
        
        chamadaAc = new ChamadaAccess();
        chamadaAc.create(chamada);
        chamada.setId(chamadaAc.pegaId(chamada.getHorario(), professor.getIdProfessor(),chamada.getData()));
        JOptionPane.showMessageDialog(null,chamada.getId());
        
    }//GEN-LAST:event_btnChamadaActionPerformed

    private void jftHorarioAUlaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jftHorarioAUlaMouseClicked
        jftHorarioAUla.setText("");
    }//GEN-LAST:event_jftHorarioAUlaMouseClicked

    private void jftHorarioAUlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftHorarioAUlaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftHorarioAUlaActionPerformed

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane2MouseClicked

    private void jtChamadasPesqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtChamadasPesqMouseClicked
        pnPesq.setVisible(false);
        jpnChamada.setVisible(true);
        
        DefaultTableModel modelo = (DefaultTableModel)jtChamadasPesq.getModel();
        
        chamadaAc = new ChamadaAccess();
        int id = chamadaAc.pegaId(modelo.getValueAt(jtChamadasPesq.getSelectedRow(), 1).toString(),professor.getIdProfessor(),modelo.getValueAt(jtChamadasPesq.getSelectedRow(), 0).toString());
        
        chamada = new Chamada();
        chamada = chamadaAc.read(id);
        
        PreencheTabela preenche1 = new PreencheTabela(jtChamadas,chamada.getId(),chamada.getIdClasse());
        
        
    }//GEN-LAST:event_jtChamadasPesqMouseClicked

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        pnMenu.setVisible(false);
        pnPesq.setVisible(false);
        pnMenuPr.setVisible(true);
        jPanel1.setVisible(false);
        jPanel2.setVisible(true);
        
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnVoltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltar1ActionPerformed
        this.dispose();
        menu = new MenuProfessor(professor);
        menu.setVisible(true);
    }//GEN-LAST:event_btnVoltar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chamadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chamadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chamadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chamadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(Professor professor) {
                new Chamadas(professor).setVisible(true);
            }

            @Override
            public void run() {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChamada;
    private javax.swing.JButton btnChamadaPesq;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnNova;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JButton btnVoltar1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jcbTurmas;
    private javax.swing.JComboBox<String> jcbTurmasPesq;
    private javax.swing.JFormattedTextField jftDataAula;
    private javax.swing.JFormattedTextField jftDataAulaPesq;
    private javax.swing.JFormattedTextField jftHorarioAUla;
    private javax.swing.JPanel jpnChamada;
    private javax.swing.JPanel jpnConteudo;
    private javax.swing.JPanel jpnEspera;
    private javax.swing.JPanel jpnJanela;
    private javax.swing.JSeparator jsDataAula;
    private javax.swing.JSeparator jsDataAula1;
    private javax.swing.JSeparator jsDataAula2;
    private javax.swing.JTable jtChamadas;
    private javax.swing.JTable jtChamadasPesq;
    private javax.swing.JLabel lblDataAula;
    private javax.swing.JLabel lblDataAula1;
    private javax.swing.JLabel lblDataAula2;
    private javax.swing.JLabel lblTurma;
    private javax.swing.JLabel lblTurma1;
    private javax.swing.JPanel pnMenu;
    private javax.swing.JPanel pnMenuPr;
    private javax.swing.JPanel pnPesq;
    private javax.swing.JPanel pnPesquisar;
    // End of variables declaration//GEN-END:variables
}
