/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.professor;

import control.connection.dataAccess.FuncoesAccess;
import control.connection.dataAccess.MateriasAccess;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import model.Professor;
import javax.swing.JOptionPane;
import view.diretor.CalendarioEscolar;

/**
 *
 * @author Aluno
 */
public class MenuProfessor extends javax.swing.JFrame {

    private static Color cor = new Color(204,204,204,100);
    private static FuncoesAccess funcao;
    private static MateriasAccess materia;
    private static Perfil perfil;
    private static Professor professor;
    private static Chamadas chamada;
    private static Notas gerenciarNotas;
    private static CalendarioEscolar calendario;
    private static Planejamento planejamento;
    
    public MenuProfessor(Professor professor) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.professor = professor;
        
        lblNome.setText(professor.getNome()+" "+professor.getSobrenome());
        lblEmail.setText(professor.getEmail());
        
        funcao = new FuncoesAccess();
        lblFuncao.setText("Função: "+funcao.read(professor.getFuncao()).getDesc());
        
        materia = new MateriasAccess();
        lblArea.setText("Disciplina: "+materia.read(professor.getMateria()).getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnPerfil = new javax.swing.JPanel();
        imgPerfil = new javax.swing.JLabel();
        lblArea = new javax.swing.JLabel();
        lblFuncao = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jpnJanela = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pnMenu = new javax.swing.JPanel();
        lblImgPlanejamento = new javax.swing.JLabel();
        lblPlanejamento = new javax.swing.JLabel();
        lblChamada = new javax.swing.JLabel();
        lblImgChamada = new javax.swing.JLabel();
        lblImgNotas = new javax.swing.JLabel();
        lblNotas = new javax.swing.JLabel();
        lblImgPerfil = new javax.swing.JLabel();
        lblPerfil = new javax.swing.JLabel();
        lblImgCalendario = new javax.swing.JLabel();
        lblCalendario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1178, 730));
        setUndecorated(true);
        getContentPane().setLayout(null);

        pnPerfil.setLayout(null);

        imgPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/user-previa.png"))); // NOI18N
        pnPerfil.add(imgPerfil);
        imgPerfil.setBounds(90, 90, 130, 150);

        lblArea.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblArea.setForeground(new java.awt.Color(255, 255, 255));
        lblArea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblArea.setText("Área: História");
        pnPerfil.add(lblArea);
        lblArea.setBounds(40, 360, 220, 19);

        lblFuncao.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblFuncao.setForeground(new java.awt.Color(255, 255, 255));
        lblFuncao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFuncao.setText("Função: Professor");
        pnPerfil.add(lblFuncao);
        lblFuncao.setBounds(40, 330, 220, 19);

        lblEmail.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmail.setText("usuario@usuario.com");
        pnPerfil.add(lblEmail);
        lblEmail.setBounds(40, 280, 220, 19);

        lblNome.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblNome.setForeground(new java.awt.Color(255, 255, 255));
        lblNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNome.setText("Nome do Usuário");
        pnPerfil.add(lblNome);
        lblNome.setBounds(40, 250, 220, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/bg-img.jpg"))); // NOI18N
        pnPerfil.add(jLabel1);
        jLabel1.setBounds(-420, 0, 770, 740);

        getContentPane().add(pnPerfil);
        pnPerfil.setBounds(0, 0, 290, 730);

        jpnJanela.setBackground(new java.awt.Color(255, 255, 255));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/cross-square-button.png"))); // NOI18N
        btnClose.setToolTipText("Fechar o programa");
        btnClose.setBorder(null);
        btnClose.setContentAreaFilled(false);
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/minimize.png"))); // NOI18N
        jButton2.setToolTipText("Minimizar o programa");
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnJanelaLayout = new javax.swing.GroupLayout(jpnJanela);
        jpnJanela.setLayout(jpnJanelaLayout);
        jpnJanelaLayout.setHorizontalGroup(
            jpnJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnJanelaLayout.createSequentialGroup()
                .addContainerGap(779, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClose)
                .addGap(35, 35, 35))
        );
        jpnJanelaLayout.setVerticalGroup(
            jpnJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnJanelaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(btnClose))
                .addContainerGap())
        );

        getContentPane().add(jpnJanela);
        jpnJanela.setBounds(290, 0, 890, 50);

        pnMenu.setBackground(new java.awt.Color(255, 255, 255));
        pnMenu.setLayout(null);

        lblImgPlanejamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImgPlanejamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/contract.png"))); // NOI18N
        lblImgPlanejamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImgPlanejamentoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblImgPlanejamentoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblImgPlanejamentoMouseExited(evt);
            }
        });
        pnMenu.add(lblImgPlanejamento);
        lblImgPlanejamento.setBounds(620, 130, 176, 172);

        lblPlanejamento.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblPlanejamento.setForeground(new java.awt.Color(0, 77, 133));
        lblPlanejamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlanejamento.setText("Meus Planejamentos");
        pnMenu.add(lblPlanejamento);
        lblPlanejamento.setBounds(630, 260, 150, 30);

        lblChamada.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblChamada.setForeground(new java.awt.Color(0, 77, 133));
        lblChamada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChamada.setText("Gerenciar Chamadas");
        pnMenu.add(lblChamada);
        lblChamada.setBounds(120, 260, 170, 30);

        lblImgChamada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImgChamada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/check-square.png"))); // NOI18N
        lblImgChamada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblImgChamada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImgChamadaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblImgChamadaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblImgChamadaMouseExited(evt);
            }
        });
        pnMenu.add(lblImgChamada);
        lblImgChamada.setBounds(120, 130, 176, 172);

        lblImgNotas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImgNotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/evaluation.png"))); // NOI18N
        lblImgNotas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImgNotasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblImgNotasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblImgNotasMouseExited(evt);
            }
        });
        pnMenu.add(lblImgNotas);
        lblImgNotas.setBounds(370, 130, 176, 172);

        lblNotas.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblNotas.setForeground(new java.awt.Color(0, 77, 133));
        lblNotas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNotas.setText("Inserir Notas");
        pnMenu.add(lblNotas);
        lblNotas.setBounds(380, 260, 150, 30);

        lblImgPerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImgPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/person.png"))); // NOI18N
        lblImgPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImgPerfilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblImgPerfilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblImgPerfilMouseExited(evt);
            }
        });
        pnMenu.add(lblImgPerfil);
        lblImgPerfil.setBounds(510, 360, 176, 172);

        lblPerfil.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblPerfil.setForeground(new java.awt.Color(0, 77, 133));
        lblPerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPerfil.setText("Acessar Perfil");
        pnMenu.add(lblPerfil);
        lblPerfil.setBounds(530, 490, 140, 19);

        lblImgCalendario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImgCalendario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/event.png"))); // NOI18N
        lblImgCalendario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImgCalendarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblImgCalendarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblImgCalendarioMouseExited(evt);
            }
        });
        pnMenu.add(lblImgCalendario);
        lblImgCalendario.setBounds(240, 350, 176, 172);

        lblCalendario.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblCalendario.setForeground(new java.awt.Color(0, 77, 133));
        lblCalendario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCalendario.setText("Calendário Escolar");
        pnMenu.add(lblCalendario);
        lblCalendario.setBounds(270, 480, 130, 19);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 77, 133));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Área de Trabalho");
        pnMenu.add(jLabel2);
        jLabel2.setBounds(320, 60, 290, 50);

        getContentPane().add(pnMenu);
        pnMenu.setBounds(290, 50, 890, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void lblImgChamadaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImgChamadaMouseEntered
        
        lblImgChamada.setBorder(BorderFactory.createLineBorder(cor, 1));
    }//GEN-LAST:event_lblImgChamadaMouseEntered

    private void lblImgChamadaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImgChamadaMouseExited
        lblImgChamada.setBorder(null);
    }//GEN-LAST:event_lblImgChamadaMouseExited

    private void lblImgNotasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImgNotasMouseEntered

        lblImgNotas.setBorder(BorderFactory.createLineBorder(cor, 1));
    }//GEN-LAST:event_lblImgNotasMouseEntered

    private void lblImgPlanejamentoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImgPlanejamentoMouseEntered
        lblImgPlanejamento.setBorder(BorderFactory.createLineBorder(cor, 1));
    }//GEN-LAST:event_lblImgPlanejamentoMouseEntered

    private void lblImgCalendarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImgCalendarioMouseEntered
        lblImgCalendario.setBorder(BorderFactory.createLineBorder(cor, 1));
    }//GEN-LAST:event_lblImgCalendarioMouseEntered

    private void lblImgPerfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImgPerfilMouseEntered
        lblImgPerfil.setBorder(BorderFactory.createLineBorder(cor, 1));
    }//GEN-LAST:event_lblImgPerfilMouseEntered

    private void lblImgPerfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImgPerfilMouseExited
        lblImgPerfil.setBorder(null);
    }//GEN-LAST:event_lblImgPerfilMouseExited

    private void lblImgCalendarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImgCalendarioMouseExited
        lblImgCalendario.setBorder(null);
    }//GEN-LAST:event_lblImgCalendarioMouseExited

    private void lblImgPlanejamentoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImgPlanejamentoMouseExited
        lblImgPlanejamento.setBorder(null);
    }//GEN-LAST:event_lblImgPlanejamentoMouseExited

    private void lblImgNotasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImgNotasMouseExited
        lblImgNotas.setBorder(null);
    }//GEN-LAST:event_lblImgNotasMouseExited

    private void lblImgPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImgPerfilMouseClicked
        perfil = new Perfil(professor);
        perfil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblImgPerfilMouseClicked

    private void lblImgChamadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImgChamadaMouseClicked
        chamada = new Chamadas(professor);
        chamada.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblImgChamadaMouseClicked

    private void lblImgNotasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImgNotasMouseClicked
        gerenciarNotas = new Notas(professor);
        gerenciarNotas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblImgNotasMouseClicked

    private void lblImgCalendarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImgCalendarioMouseClicked
        calendario = new CalendarioEscolar();
        calendario.setVisible(true);
    }//GEN-LAST:event_lblImgCalendarioMouseClicked

    private void lblImgPlanejamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImgPlanejamentoMouseClicked
        planejamento = new Planejamento(professor);
        planejamento.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblImgPlanejamentoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(Professor professor) {
                new MenuProfessor(professor).setVisible(true);
            }

            @Override
            public void run() {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel imgPerfil;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jpnJanela;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblCalendario;
    private javax.swing.JLabel lblChamada;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFuncao;
    private javax.swing.JLabel lblImgCalendario;
    private javax.swing.JLabel lblImgChamada;
    private javax.swing.JLabel lblImgNotas;
    private javax.swing.JLabel lblImgPerfil;
    private javax.swing.JLabel lblImgPlanejamento;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNotas;
    private javax.swing.JLabel lblPerfil;
    private javax.swing.JLabel lblPlanejamento;
    private javax.swing.JPanel pnMenu;
    private javax.swing.JPanel pnPerfil;
    // End of variables declaration//GEN-END:variables
}
