package view;

import control.connection.dataAccess.CategoriaAccess;
import control.connection.dataAccess.CidadeAccess;
import control.connection.dataAccess.EstadoAccess;
import control.connection.dataAccess.UsuarioAccess;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.CategoriaUsuario;
import model.Cidade;
import model.Estado;
import model.Usuario;
import view.aluno.CadastroEspecificoAluno;
import view.diretor.MenuDiretor;
import view.professor.CadastroEspecificoProfessor;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author benedito
 */
public class CadastroGeral extends javax.swing.JFrame {

    String genero="M";
    private static Login login = new Login();
    
    public CadastroGeral() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        
        CategoriaAccess categorias = new CategoriaAccess();
        for(CategoriaUsuario categoria:categorias.read())
        {
            jcbCategoria.addItem(categoria.getNome());
        }   
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrGenero = new javax.swing.ButtonGroup();
        jpnLogo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();
        jpnCadastro = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jsLinhaNome = new javax.swing.JSeparator();
        lblSobrenome = new javax.swing.JLabel();
        txtSobrenome = new javax.swing.JTextField();
        jsLinhaSobrenome = new javax.swing.JSeparator();
        lblDataNasc = new javax.swing.JLabel();
        jsDataNasc = new javax.swing.JSeparator();
        lblSobrenome1 = new javax.swing.JLabel();
        jsLinhaSobrenome1 = new javax.swing.JSeparator();
        jftTelefone = new javax.swing.JFormattedTextField();
        jftDataNasc = new javax.swing.JFormattedTextField();
        lblGenero = new javax.swing.JLabel();
        rdBtnMasculino = new javax.swing.JRadioButton();
        rdBtnFeminino = new javax.swing.JRadioButton();
        rdBtnOutros = new javax.swing.JRadioButton();
        lblRG = new javax.swing.JLabel();
        jftRG = new javax.swing.JFormattedTextField();
        jsLinhaRG = new javax.swing.JSeparator();
        lblCPF = new javax.swing.JLabel();
        jftCPF = new javax.swing.JFormattedTextField();
        jsLinhaCPF = new javax.swing.JSeparator();
        lblEstado = new javax.swing.JLabel();
        jcbEstado = new javax.swing.JComboBox<>();
        lblCidade = new javax.swing.JLabel();
        jcbCidade = new javax.swing.JComboBox<>();
        lblRua = new javax.swing.JLabel();
        txtRua = new javax.swing.JTextField();
        jsLinhaRua = new javax.swing.JSeparator();
        lblNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jsLinhaNumero = new javax.swing.JSeparator();
        lblBairro = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        jsLinhaBairro = new javax.swing.JSeparator();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jsLinhaEmail = new javax.swing.JSeparator();
        lblSenha = new javax.swing.JLabel();
        jsSenha = new javax.swing.JSeparator();
        jpSenha = new javax.swing.JPasswordField();
        btnCadastrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jcbCategoria = new javax.swing.JComboBox<>();
        lblSenha1 = new javax.swing.JLabel();
        jpnJanela = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1178, 800));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1178, 800));
        setResizable(false);
        getContentPane().setLayout(null);

        jpnLogo.setBackground(new java.awt.Color(255, 255, 255));
        jpnLogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jpnLogo.setPreferredSize(new java.awt.Dimension(290, 625));
        jpnLogo.setLayout(null);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/LOGO-PEQUENO-BRANCO.png"))); // NOI18N
        jpnLogo.add(lblLogo);
        lblLogo.setBounds(30, 290, 330, 160);

        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/bg-img.jpg"))); // NOI18N
        jpnLogo.add(lblBack);
        lblBack.setBounds(-250, -160, 810, 1000);

        getContentPane().add(jpnLogo);
        jpnLogo.setBounds(0, 0, 390, 820);

        jpnCadastro.setBackground(new java.awt.Color(255, 255, 255));
        jpnCadastro.setForeground(new java.awt.Color(153, 153, 153));
        jpnCadastro.setLayout(null);

        lblNome.setBackground(new java.awt.Color(27, 144, 240));
        lblNome.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblNome.setForeground(new java.awt.Color(0, 77, 133));
        lblNome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/user.png"))); // NOI18N
        lblNome.setText("Nome");
        jpnCadastro.add(lblNome);
        lblNome.setBounds(80, 80, 290, 30);

        txtNome.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txtNome.setForeground(new java.awt.Color(153, 153, 153));
        txtNome.setText("Clique para escrever seu nome");
        txtNome.setBorder(null);
        txtNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNomeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNomeMousePressed(evt);
            }
        });
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        jpnCadastro.add(txtNome);
        txtNome.setBounds(80, 110, 290, 30);

        jsLinhaNome.setBackground(new java.awt.Color(102, 102, 102));
        jsLinhaNome.setForeground(new java.awt.Color(255, 255, 255));
        jpnCadastro.add(jsLinhaNome);
        jsLinhaNome.setBounds(80, 140, 290, 30);

        lblSobrenome.setBackground(new java.awt.Color(27, 144, 240));
        lblSobrenome.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblSobrenome.setForeground(new java.awt.Color(0, 77, 133));
        lblSobrenome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/user.png"))); // NOI18N
        lblSobrenome.setText("Sobrenome");
        jpnCadastro.add(lblSobrenome);
        lblSobrenome.setBounds(430, 80, 290, 30);

        txtSobrenome.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txtSobrenome.setForeground(new java.awt.Color(153, 153, 153));
        txtSobrenome.setText("Clique para escrever seu sobrenome");
        txtSobrenome.setBorder(null);
        txtSobrenome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSobrenomeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtSobrenomeMousePressed(evt);
            }
        });
        txtSobrenome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSobrenomeActionPerformed(evt);
            }
        });
        jpnCadastro.add(txtSobrenome);
        txtSobrenome.setBounds(430, 110, 290, 30);

        jsLinhaSobrenome.setBackground(new java.awt.Color(102, 102, 102));
        jsLinhaSobrenome.setForeground(new java.awt.Color(255, 255, 255));
        jpnCadastro.add(jsLinhaSobrenome);
        jsLinhaSobrenome.setBounds(430, 140, 290, 30);

        lblDataNasc.setBackground(new java.awt.Color(27, 144, 240));
        lblDataNasc.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblDataNasc.setForeground(new java.awt.Color(0, 77, 133));
        lblDataNasc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/calendar.png"))); // NOI18N
        lblDataNasc.setText("Data de Nascimento");
        jpnCadastro.add(lblDataNasc);
        lblDataNasc.setBounds(80, 170, 290, 30);

        jsDataNasc.setBackground(new java.awt.Color(102, 102, 102));
        jsDataNasc.setForeground(new java.awt.Color(255, 255, 255));
        jpnCadastro.add(jsDataNasc);
        jsDataNasc.setBounds(80, 230, 290, 30);

        lblSobrenome1.setBackground(new java.awt.Color(27, 144, 240));
        lblSobrenome1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblSobrenome1.setForeground(new java.awt.Color(0, 77, 133));
        lblSobrenome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/phone-call.png"))); // NOI18N
        lblSobrenome1.setText("Telefone");
        jpnCadastro.add(lblSobrenome1);
        lblSobrenome1.setBounds(430, 170, 290, 30);

        jsLinhaSobrenome1.setBackground(new java.awt.Color(102, 102, 102));
        jsLinhaSobrenome1.setForeground(new java.awt.Color(255, 255, 255));
        jpnCadastro.add(jsLinhaSobrenome1);
        jsLinhaSobrenome1.setBounds(430, 230, 290, 30);

        jftTelefone.setBorder(null);
        jftTelefone.setForeground(new java.awt.Color(153, 153, 153));
        try {
            jftTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftTelefone.setText("(00)00000-0000");
        jftTelefone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jftTelefoneMouseClicked(evt);
            }
        });
        jpnCadastro.add(jftTelefone);
        jftTelefone.setBounds(430, 200, 290, 30);

        jftDataNasc.setBorder(null);
        jftDataNasc.setForeground(new java.awt.Color(153, 153, 153));
        try {
            jftDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftDataNasc.setText("00/00/0000");
        jftDataNasc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jftDataNascMouseClicked(evt);
            }
        });
        jftDataNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftDataNascActionPerformed(evt);
            }
        });
        jpnCadastro.add(jftDataNasc);
        jftDataNasc.setBounds(80, 200, 290, 30);

        lblGenero.setBackground(new java.awt.Color(27, 144, 240));
        lblGenero.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblGenero.setForeground(new java.awt.Color(0, 77, 133));
        lblGenero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/gender.png"))); // NOI18N
        lblGenero.setText("Gênero");
        jpnCadastro.add(lblGenero);
        lblGenero.setBounds(80, 260, 290, 30);

        btnGrGenero.add(rdBtnMasculino);
        rdBtnMasculino.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        rdBtnMasculino.setForeground(new java.awt.Color(153, 153, 153));
        rdBtnMasculino.setSelected(true);
        rdBtnMasculino.setText("Masculino");
        rdBtnMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBtnMasculinoActionPerformed(evt);
            }
        });
        jpnCadastro.add(rdBtnMasculino);
        rdBtnMasculino.setBounds(80, 300, 81, 23);

        btnGrGenero.add(rdBtnFeminino);
        rdBtnFeminino.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        rdBtnFeminino.setForeground(new java.awt.Color(153, 153, 153));
        rdBtnFeminino.setText("Feminino");
        rdBtnFeminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBtnFemininoActionPerformed(evt);
            }
        });
        jpnCadastro.add(rdBtnFeminino);
        rdBtnFeminino.setBounds(190, 300, 73, 23);

        btnGrGenero.add(rdBtnOutros);
        rdBtnOutros.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        rdBtnOutros.setForeground(new java.awt.Color(153, 153, 153));
        rdBtnOutros.setText("Outros");
        rdBtnOutros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBtnOutrosActionPerformed(evt);
            }
        });
        jpnCadastro.add(rdBtnOutros);
        rdBtnOutros.setBounds(300, 300, 70, 23);

        lblRG.setBackground(new java.awt.Color(27, 144, 240));
        lblRG.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblRG.setForeground(new java.awt.Color(0, 77, 133));
        lblRG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/id-card.png"))); // NOI18N
        lblRG.setText("RG");
        jpnCadastro.add(lblRG);
        lblRG.setBounds(430, 260, 290, 30);

        jftRG.setBorder(null);
        jftRG.setForeground(new java.awt.Color(153, 153, 153));
        try {
            jftRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftRG.setText("00.000.000-0");
        jftRG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jftRGMouseClicked(evt);
            }
        });
        jpnCadastro.add(jftRG);
        jftRG.setBounds(430, 290, 290, 30);

        jsLinhaRG.setBackground(new java.awt.Color(102, 102, 102));
        jsLinhaRG.setForeground(new java.awt.Color(255, 255, 255));
        jpnCadastro.add(jsLinhaRG);
        jsLinhaRG.setBounds(430, 320, 290, 30);

        lblCPF.setBackground(new java.awt.Color(27, 144, 240));
        lblCPF.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblCPF.setForeground(new java.awt.Color(0, 77, 133));
        lblCPF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/id-card.png"))); // NOI18N
        lblCPF.setText("CPF");
        jpnCadastro.add(lblCPF);
        lblCPF.setBounds(80, 340, 290, 30);

        jftCPF.setBorder(null);
        jftCPF.setForeground(new java.awt.Color(153, 153, 153));
        try {
            jftCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftCPF.setText("000.000.000-00");
        jftCPF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jftCPFMouseClicked(evt);
            }
        });
        jftCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftCPFActionPerformed(evt);
            }
        });
        jpnCadastro.add(jftCPF);
        jftCPF.setBounds(80, 370, 290, 30);

        jsLinhaCPF.setBackground(new java.awt.Color(102, 102, 102));
        jsLinhaCPF.setForeground(new java.awt.Color(255, 255, 255));
        jpnCadastro.add(jsLinhaCPF);
        jsLinhaCPF.setBounds(80, 400, 290, 30);

        lblEstado.setBackground(new java.awt.Color(27, 144, 240));
        lblEstado.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblEstado.setForeground(new java.awt.Color(0, 77, 133));
        lblEstado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/marker.png"))); // NOI18N
        lblEstado.setText("Estado");
        jpnCadastro.add(lblEstado);
        lblEstado.setBounds(430, 340, 290, 30);

        jcbEstado.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jcbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha um estado" }));
        jcbEstado.setToolTipText("");
        jcbEstado.setBorder(null);
        jcbEstado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbEstadoItemStateChanged(evt);
            }
        });
        jcbEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcbEstadoMouseClicked(evt);
            }
        });
        jcbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbEstadoActionPerformed(evt);
            }
        });
        jpnCadastro.add(jcbEstado);
        jcbEstado.setBounds(430, 370, 290, 30);

        lblCidade.setBackground(new java.awt.Color(27, 144, 240));
        lblCidade.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblCidade.setForeground(new java.awt.Color(0, 77, 133));
        lblCidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/marker.png"))); // NOI18N
        lblCidade.setText("Cidade");
        jpnCadastro.add(lblCidade);
        lblCidade.setBounds(80, 420, 290, 30);

        jcbCidade.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jcbCidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha primeiro um estado" }));
        jcbCidade.setToolTipText("");
        jcbCidade.setBorder(null);
        jpnCadastro.add(jcbCidade);
        jcbCidade.setBounds(80, 450, 290, 30);

        lblRua.setBackground(new java.awt.Color(27, 144, 240));
        lblRua.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblRua.setForeground(new java.awt.Color(0, 77, 133));
        lblRua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/marker.png"))); // NOI18N
        lblRua.setText("Rua");
        jpnCadastro.add(lblRua);
        lblRua.setBounds(430, 420, 290, 30);

        txtRua.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txtRua.setForeground(new java.awt.Color(153, 153, 153));
        txtRua.setText("Clique para escrever sua rua");
        txtRua.setBorder(null);
        txtRua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRuaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtRuaMousePressed(evt);
            }
        });
        txtRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRuaActionPerformed(evt);
            }
        });
        jpnCadastro.add(txtRua);
        txtRua.setBounds(430, 450, 290, 30);

        jsLinhaRua.setBackground(new java.awt.Color(102, 102, 102));
        jsLinhaRua.setForeground(new java.awt.Color(255, 255, 255));
        jpnCadastro.add(jsLinhaRua);
        jsLinhaRua.setBounds(430, 480, 290, 30);

        lblNumero.setBackground(new java.awt.Color(27, 144, 240));
        lblNumero.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblNumero.setForeground(new java.awt.Color(0, 77, 133));
        lblNumero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/marker.png"))); // NOI18N
        lblNumero.setText("Número");
        jpnCadastro.add(lblNumero);
        lblNumero.setBounds(80, 500, 90, 30);

        txtNumero.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txtNumero.setForeground(new java.awt.Color(153, 153, 153));
        txtNumero.setBorder(null);
        txtNumero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNumeroMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNumeroMousePressed(evt);
            }
        });
        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });
        jpnCadastro.add(txtNumero);
        txtNumero.setBounds(80, 530, 90, 30);

        jsLinhaNumero.setBackground(new java.awt.Color(102, 102, 102));
        jsLinhaNumero.setForeground(new java.awt.Color(255, 255, 255));
        jpnCadastro.add(jsLinhaNumero);
        jsLinhaNumero.setBounds(80, 560, 90, 30);

        lblBairro.setBackground(new java.awt.Color(27, 144, 240));
        lblBairro.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblBairro.setForeground(new java.awt.Color(0, 77, 133));
        lblBairro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/marker.png"))); // NOI18N
        lblBairro.setText("Bairro");
        jpnCadastro.add(lblBairro);
        lblBairro.setBounds(190, 500, 90, 30);

        txtBairro.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txtBairro.setForeground(new java.awt.Color(153, 153, 153));
        txtBairro.setText("Clique para escrever seu bairro");
        txtBairro.setBorder(null);
        txtBairro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBairroMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtBairroMousePressed(evt);
            }
        });
        txtBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBairroActionPerformed(evt);
            }
        });
        jpnCadastro.add(txtBairro);
        txtBairro.setBounds(190, 530, 180, 30);

        jsLinhaBairro.setBackground(new java.awt.Color(102, 102, 102));
        jsLinhaBairro.setForeground(new java.awt.Color(255, 255, 255));
        jpnCadastro.add(jsLinhaBairro);
        jsLinhaBairro.setBounds(190, 560, 180, 30);

        lblEmail.setBackground(new java.awt.Color(27, 144, 240));
        lblEmail.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(0, 77, 133));
        lblEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/mail.png"))); // NOI18N
        lblEmail.setText("Email");
        jpnCadastro.add(lblEmail);
        lblEmail.setBounds(430, 500, 290, 30);

        txtEmail.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(153, 153, 153));
        txtEmail.setText("Clique para escrever seu email");
        txtEmail.setBorder(null);
        txtEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEmailMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtEmailMousePressed(evt);
            }
        });
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jpnCadastro.add(txtEmail);
        txtEmail.setBounds(430, 530, 290, 30);

        jsLinhaEmail.setBackground(new java.awt.Color(102, 102, 102));
        jsLinhaEmail.setForeground(new java.awt.Color(255, 255, 255));
        jpnCadastro.add(jsLinhaEmail);
        jsLinhaEmail.setBounds(430, 560, 290, 30);

        lblSenha.setBackground(new java.awt.Color(27, 144, 240));
        lblSenha.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(0, 77, 133));
        lblSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/maintenance.png"))); // NOI18N
        lblSenha.setText("Categoria do usuário");
        jpnCadastro.add(lblSenha);
        lblSenha.setBounds(430, 590, 290, 30);

        jsSenha.setBackground(new java.awt.Color(102, 102, 102));
        jsSenha.setForeground(new java.awt.Color(255, 255, 255));
        jpnCadastro.add(jsSenha);
        jsSenha.setBounds(80, 650, 290, 30);

        jpSenha.setForeground(new java.awt.Color(153, 153, 153));
        jpSenha.setText("jPasswordField1");
        jpSenha.setBorder(null);
        jpSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpSenhaMouseClicked(evt);
            }
        });
        jpnCadastro.add(jpSenha);
        jpSenha.setBounds(80, 620, 290, 30);

        btnCadastrar.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(0, 77, 133));
        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/plus.png"))); // NOI18N
        btnCadastrar.setText("CADASTRAR");
        btnCadastrar.setActionCommand("btnCadastrar");
        btnCadastrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 77, 133), 1, true));
        btnCadastrar.setContentAreaFilled(false);
        btnCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastrar.setFocusPainted(false);
        btnCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseExited(evt);
            }
        });
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        jpnCadastro.add(btnCadastrar);
        btnCadastrar.setBounds(510, 680, 210, 60);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 77, 133));
        jLabel1.setText("CADASTRE-SE");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jpnCadastro.add(jLabel1);
        jLabel1.setBounds(270, 10, 240, 45);

        jcbCategoria.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jpnCadastro.add(jcbCategoria);
        jcbCategoria.setBounds(430, 620, 290, 30);

        lblSenha1.setBackground(new java.awt.Color(27, 144, 240));
        lblSenha1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblSenha1.setForeground(new java.awt.Color(0, 77, 133));
        lblSenha1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/lock.png"))); // NOI18N
        lblSenha1.setText("Senha");
        jpnCadastro.add(lblSenha1);
        lblSenha1.setBounds(80, 590, 290, 30);

        getContentPane().add(jpnCadastro);
        jpnCadastro.setBounds(390, 45, 790, 770);

        jpnJanela.setBackground(new java.awt.Color(255, 255, 255));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/cross-square-button.png"))); // NOI18N
        btnClose.setToolTipText("Fechar o programa");
        btnClose.setBorder(null);
        btnClose.setContentAreaFilled(false);
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/minimize.png"))); // NOI18N
        jButton2.setToolTipText("Minimizar o programa");
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnJanelaLayout = new javax.swing.GroupLayout(jpnJanela);
        jpnJanela.setLayout(jpnJanelaLayout);
        jpnJanelaLayout.setHorizontalGroup(
            jpnJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnJanelaLayout.createSequentialGroup()
                .addContainerGap(679, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClose)
                .addGap(35, 35, 35))
        );
        jpnJanelaLayout.setVerticalGroup(
            jpnJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnJanelaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(btnClose))
                .addContainerGap())
        );

        getContentPane().add(jpnJanela);
        jpnJanela.setBounds(390, 0, 790, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNomeMouseClicked
        this.txtNome.setText("");
    }//GEN-LAST:event_txtNomeMouseClicked

    private void txtNomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNomeMousePressed
        
    }//GEN-LAST:event_txtNomeMousePressed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtSobrenomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSobrenomeMouseClicked
        this.txtSobrenome.setText("");
    }//GEN-LAST:event_txtSobrenomeMouseClicked

    private void txtSobrenomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSobrenomeMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSobrenomeMousePressed

    private void txtSobrenomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSobrenomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSobrenomeActionPerformed

    private void jftCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftCPFActionPerformed

    private void txtRuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRuaMouseClicked
        txtRua.setText("");
    }//GEN-LAST:event_txtRuaMouseClicked

    private void txtRuaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRuaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuaMousePressed

    private void txtRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuaActionPerformed

    private void txtNumeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNumeroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroMouseClicked

    private void txtNumeroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNumeroMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroMousePressed

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void txtBairroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBairroMouseClicked
        txtBairro.setText("");
    }//GEN-LAST:event_txtBairroMouseClicked

    private void txtBairroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBairroMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBairroMousePressed

    private void txtBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBairroActionPerformed

    private void txtEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmailMouseClicked
        txtEmail.setText("");
    }//GEN-LAST:event_txtEmailMouseClicked

    private void txtEmailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmailMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailMousePressed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnCadastrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseEntered
       btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/plus-blue.png")));
    }//GEN-LAST:event_btnCadastrarMouseEntered

    private void btnCadastrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseExited
        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/plus.png")));
    }//GEN-LAST:event_btnCadastrarMouseExited

    private void jftDataNascMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jftDataNascMouseClicked
        this.jftDataNasc.setText("");
    }//GEN-LAST:event_jftDataNascMouseClicked

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jftDataNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftDataNascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftDataNascActionPerformed

    private void jftTelefoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jftTelefoneMouseClicked
        this.jftTelefone.setText("");
    }//GEN-LAST:event_jftTelefoneMouseClicked

    private void jftRGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jftRGMouseClicked
        this.jftRG.setText("");
    }//GEN-LAST:event_jftRGMouseClicked

    private void jftCPFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jftCPFMouseClicked
        this.jftCPF.setText("");
    }//GEN-LAST:event_jftCPFMouseClicked

    private void jpSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpSenhaMouseClicked
        jpSenha.setText("");
    }//GEN-LAST:event_jpSenhaMouseClicked

    private void jcbEstadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbEstadoMouseClicked
        jcbEstado.removeAllItems();
        EstadoAccess estadoAc = new EstadoAccess();
        for(Estado estado:estadoAc.read())
        {
            jcbEstado.addItem(estado.getNome());
        }   
    }//GEN-LAST:event_jcbEstadoMouseClicked

    private void jcbEstadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbEstadoItemStateChanged
       jcbCidade.removeAllItems();
       
       int estado = (jcbEstado.getSelectedIndex()+1);
               
       CidadeAccess cidadeAc = new CidadeAccess();
        
       for(Cidade cidade:cidadeAc.read(estado))
       {
            jcbCidade.addItem(cidade.getNome());
       }
        
    }//GEN-LAST:event_jcbEstadoItemStateChanged

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        Usuario usuario = new Usuario();
        UsuarioAccess acesso = new UsuarioAccess();
        int estado = jcbEstado.getSelectedIndex()+1;
        int cidade = jcbCidade.getSelectedIndex()+1;
        if
        (txtNome.getText().length()>0 && txtSobrenome.getText().length()>0 
         && txtRua.getText().length()>0 && txtBairro.getText().length()>0
         && txtEmail.getText().length()>0 && txtNumero.getText().length()>0
         && jftRG.getText().trim().length()==12 && jftCPF.getText().trim().length()==14
         && jftTelefone.getText().trim().length()==14 && jpSenha.getText().toString().length()>0
         && jftDataNasc.getText().trim().length()>0)
        {
            usuario.setNome(txtNome.getText());
            
            usuario.setSobrenome(txtSobrenome.getText());
            
            usuario.setCPF(jftCPF.getText());
            
            usuario.setRG(jftRG.getText());
            
            usuario.setTelefone(jftTelefone.getText());
           
            usuario.setCidade(cidade);
            
            usuario.setEstado(estado);
            
            usuario.setNum(Integer.parseInt(txtNumero.getText()));
            
            usuario.setBairro(txtBairro.getText());
            
            usuario.setRua(txtRua.getText());
            
            usuario.setEmail(txtEmail.getText());
            
            usuario.setSenha(jpSenha.getText());
            
            usuario.setDataNasc(jftDataNasc.getText());
           
            usuario.setGenero(genero);

            usuario.setCategoria(jcbCategoria.getSelectedIndex()+1);

            acesso.create(usuario);
            
            usuario.setId(acesso.pegaId(usuario.getEmail()));
            
            switch (jcbCategoria.getSelectedIndex()+1) {
                case 1:
                    MenuDiretor menu = new MenuDiretor(usuario);
                    menu.setVisible(true);
                    break;
                case 2:
                    {
                        CadastroEspecificoAluno cadastroEsp = new CadastroEspecificoAluno(usuario);
                        cadastroEsp.setVisible(true);
                        break;
                    }
                default:
                    {
                        CadastroEspecificoProfessor cadastroEsp = new CadastroEspecificoProfessor(usuario);
                        cadastroEsp.setVisible(true);
                        break;
                    }
            }
            this.dispose();
            
        }
        else
        {
            JOptionPane.showMessageDialog(null,"PREENCHA TODOS OS CAMPOS","ERRO",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void rdBtnFemininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtnFemininoActionPerformed
        genero="F";
    }//GEN-LAST:event_rdBtnFemininoActionPerformed

    private void rdBtnMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtnMasculinoActionPerformed
        genero="M";
    }//GEN-LAST:event_rdBtnMasculinoActionPerformed

    private void rdBtnOutrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtnOutrosActionPerformed
        genero="O";
    }//GEN-LAST:event_rdBtnOutrosActionPerformed

    private void jcbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbEstadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroGeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroGeral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnClose;
    private javax.swing.ButtonGroup btnGrGenero;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> jcbCategoria;
    private javax.swing.JComboBox<String> jcbCidade;
    private javax.swing.JComboBox<String> jcbEstado;
    private javax.swing.JFormattedTextField jftCPF;
    private javax.swing.JFormattedTextField jftDataNasc;
    private javax.swing.JFormattedTextField jftRG;
    private javax.swing.JFormattedTextField jftTelefone;
    private javax.swing.JPasswordField jpSenha;
    private javax.swing.JPanel jpnCadastro;
    private javax.swing.JPanel jpnJanela;
    private javax.swing.JPanel jpnLogo;
    private javax.swing.JSeparator jsDataNasc;
    private javax.swing.JSeparator jsLinhaBairro;
    private javax.swing.JSeparator jsLinhaCPF;
    private javax.swing.JSeparator jsLinhaEmail;
    private javax.swing.JSeparator jsLinhaNome;
    private javax.swing.JSeparator jsLinhaNumero;
    private javax.swing.JSeparator jsLinhaRG;
    private javax.swing.JSeparator jsLinhaRua;
    private javax.swing.JSeparator jsLinhaSobrenome;
    private javax.swing.JSeparator jsLinhaSobrenome1;
    private javax.swing.JSeparator jsSenha;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblDataNasc;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblRG;
    private javax.swing.JLabel lblRua;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblSenha1;
    private javax.swing.JLabel lblSobrenome;
    private javax.swing.JLabel lblSobrenome1;
    private javax.swing.JRadioButton rdBtnFeminino;
    private javax.swing.JRadioButton rdBtnMasculino;
    private javax.swing.JRadioButton rdBtnOutros;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRua;
    private javax.swing.JTextField txtSobrenome;
    // End of variables declaration//GEN-END:variables
}
