/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.connection.dataAccess.AlunoAccess;
import control.connection.dataAccess.ProfessorAccess;
import control.connection.dataAccess.UsuarioAccess;
import javax.swing.JFrame;
import model.Aluno;
import model.Diretor;
import model.Professor;
import model.Usuario;
import view.aluno.MenuAluno;
import view.diretor.MenuDiretor;
import view.professor.MenuProfessor;

/**
 *
 * @author Aluno
 */
public class Login extends JFrame {

    static Usuario usuario;
    static MenuDiretor menuDiretor;
    static UsuarioAccess acesso;
    static ProfessorAccess professorAc;
    static Professor professor;
    static AlunoAccess alunoAc; 
    static Aluno aluno;
    static MenuAluno menuAluno;
    static MenuProfessor menuProfessor;
    static CadastroGeral cadastro = new CadastroGeral();
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnJanela = new javax.swing.JPanel();
        btnMinimize = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jpnLogin = new javax.swing.JPanel();
        lblSenha = new javax.swing.JLabel();
        jpSenha = new javax.swing.JPasswordField();
        jsSenha = new javax.swing.JSeparator();
        lblEmail = new javax.swing.JLabel();
        jsLinhaEmail = new javax.swing.JSeparator();
        txtEmail = new javax.swing.JTextField();
        btnCadastro = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jpnLogo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1178, 730));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1178, 730));
        setResizable(false);
        getContentPane().setLayout(null);

        jpnJanela.setBackground(new java.awt.Color(255, 255, 255));

        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/minimize.png"))); // NOI18N
        btnMinimize.setToolTipText("Minimizar o programa");
        btnMinimize.setBorder(null);
        btnMinimize.setContentAreaFilled(false);
        btnMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizeActionPerformed(evt);
            }
        });

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/cross-square-button.png"))); // NOI18N
        btnClose.setToolTipText("Fechar o programa");
        btnClose.setBorder(null);
        btnClose.setContentAreaFilled(false);
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnJanelaLayout = new javax.swing.GroupLayout(jpnJanela);
        jpnJanela.setLayout(jpnJanelaLayout);
        jpnJanelaLayout.setHorizontalGroup(
            jpnJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnJanelaLayout.createSequentialGroup()
                .addContainerGap(675, Short.MAX_VALUE)
                .addComponent(btnMinimize)
                .addGap(18, 18, 18)
                .addComponent(btnClose)
                .addGap(31, 31, 31))
        );
        jpnJanelaLayout.setVerticalGroup(
            jpnJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnJanelaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMinimize)
                    .addComponent(btnClose))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jpnJanela);
        jpnJanela.setBounds(390, 0, 790, 50);

        jpnLogin.setBackground(new java.awt.Color(255, 255, 255));
        jpnLogin.setLayout(null);

        lblSenha.setBackground(new java.awt.Color(27, 144, 240));
        lblSenha.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(0, 77, 133));
        lblSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/lock.png"))); // NOI18N
        lblSenha.setText("Senha");
        jpnLogin.add(lblSenha);
        lblSenha.setBounds(240, 350, 290, 30);

        jpSenha.setForeground(new java.awt.Color(153, 153, 153));
        jpSenha.setText("jPasswordField1");
        jpSenha.setBorder(null);
        jpSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpSenhaMouseClicked(evt);
            }
        });
        jpSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpSenhaActionPerformed(evt);
            }
        });
        jpnLogin.add(jpSenha);
        jpSenha.setBounds(240, 380, 290, 30);

        jsSenha.setBackground(new java.awt.Color(102, 102, 102));
        jsSenha.setForeground(new java.awt.Color(255, 255, 255));
        jpnLogin.add(jsSenha);
        jsSenha.setBounds(240, 410, 290, 30);

        lblEmail.setBackground(new java.awt.Color(27, 144, 240));
        lblEmail.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(0, 77, 133));
        lblEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/mail.png"))); // NOI18N
        lblEmail.setText("Email");
        jpnLogin.add(lblEmail);
        lblEmail.setBounds(240, 260, 290, 30);

        jsLinhaEmail.setBackground(new java.awt.Color(102, 102, 102));
        jsLinhaEmail.setForeground(new java.awt.Color(255, 255, 255));
        jpnLogin.add(jsLinhaEmail);
        jsLinhaEmail.setBounds(240, 320, 290, 30);

        txtEmail.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(153, 153, 153));
        txtEmail.setText("Clique para escrever seu email");
        txtEmail.setBorder(null);
        txtEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEmailMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtEmailMousePressed(evt);
            }
        });
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jpnLogin.add(txtEmail);
        txtEmail.setBounds(240, 290, 290, 30);

        btnCadastro.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btnCadastro.setForeground(new java.awt.Color(0, 77, 133));
        btnCadastro.setText("CADASTRE-SE");
        btnCadastro.setActionCommand("btnCadastrar");
        btnCadastro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 77, 133), 1, true));
        btnCadastro.setContentAreaFilled(false);
        btnCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastro.setFocusPainted(false);
        btnCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCadastroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCadastroMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCadastroMousePressed(evt);
            }
        });
        jpnLogin.add(btnCadastro);
        btnCadastro.setBounds(370, 540, 160, 30);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 77, 133));
        jLabel2.setText("LOGIN");
        jpnLogin.add(jLabel2);
        jLabel2.setBounds(340, 180, 120, 50);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 77, 133));
        jLabel1.setText("Ainda não possui cadastro?");
        jpnLogin.add(jLabel1);
        jLabel1.setBounds(370, 520, 160, 15);

        btnLogin.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(0, 77, 133));
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/login.png"))); // NOI18N
        btnLogin.setText("LOGIN");
        btnLogin.setActionCommand("btnCadastrar");
        btnLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 77, 133), 1, true));
        btnLogin.setContentAreaFilled(false);
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.setFocusPainted(false);
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginMouseExited(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jpnLogin.add(btnLogin);
        btnLogin.setBounds(230, 460, 300, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/user-login.png"))); // NOI18N
        jpnLogin.add(jLabel3);
        jLabel3.setBounds(360, 90, 120, 90);

        getContentPane().add(jpnLogin);
        jpnLogin.setBounds(390, 50, 790, 680);

        jpnLogo.setBackground(new java.awt.Color(255, 255, 255));
        jpnLogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jpnLogo.setPreferredSize(new java.awt.Dimension(290, 625));
        jpnLogo.setLayout(null);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/LOGO-PEQUENO-BRANCO.png"))); // NOI18N
        jpnLogo.add(lblLogo);
        lblLogo.setBounds(30, 290, 330, 160);

        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/bg-img.jpg"))); // NOI18N
        jpnLogo.add(lblBack);
        lblBack.setBounds(-270, 0, 730, 730);

        getContentPane().add(jpnLogo);
        jpnLogo.setBounds(0, 0, 390, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizeActionPerformed
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void txtEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmailMouseClicked
        txtEmail.setText("");
    }//GEN-LAST:event_txtEmailMouseClicked

    private void txtEmailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmailMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailMousePressed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void jpSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpSenhaMouseClicked
        jpSenha.setText("");
    }//GEN-LAST:event_jpSenhaMouseClicked

    private void btnCadastroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastroMouseEntered
        
    }//GEN-LAST:event_btnCadastroMouseEntered

    private void btnCadastroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastroMouseExited
       
    }//GEN-LAST:event_btnCadastroMouseExited

    private void btnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseEntered
         btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/login-blue.png")));
    }//GEN-LAST:event_btnLoginMouseEntered

    private void btnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseExited
         btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/login.png")));
    }//GEN-LAST:event_btnLoginMouseExited

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        acesso = new UsuarioAccess();
        
        if(acesso.verifica(txtEmail.getText(), jpSenha.getText())==true)
        {
            usuario = new Usuario();
            usuario = acesso.read(txtEmail.getText());
            switch (usuario.getCategoria()) {
                case 1:
                    //diretor
                    menuDiretor = new MenuDiretor(usuario);
                    menuDiretor.setVisible(true);
                    
                    break;
                case 2:
                    {
                        //aluno
                        alunoAc = new AlunoAccess();
                        aluno = new Aluno();
                        aluno = alunoAc.readGeral(usuario.getId(),usuario);
                        menuAluno = new MenuAluno(aluno);
                        menuAluno.setVisible(true);
                        this.dispose();
                        break;
                    }
                default:
                    {
                        //professor
                        professorAc = new ProfessorAccess();
                        professor = new Professor();
                        professor = professorAc.readGeral(usuario.getId(),usuario);
                        menuProfessor = new MenuProfessor(professor);
                        menuProfessor.setVisible(true);
                        this.dispose();
                        break;
                    }
            }
            
            
            
            
            
        }
        
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void jpSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpSenhaActionPerformed

    private void btnCadastroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastroMousePressed
        cadastro.setVisible(true);
    }//GEN-LAST:event_btnCadastroMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnMinimize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jpSenha;
    private javax.swing.JPanel jpnJanela;
    private javax.swing.JPanel jpnLogin;
    private javax.swing.JPanel jpnLogo;
    private javax.swing.JSeparator jsLinhaEmail;
    private javax.swing.JSeparator jsSenha;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
}
