/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.professor.nota;

import javax.swing.table.DefaultTableModel;
import model.PreencheTabela;

/**
 *
 * @author benedito
 */
public class InsercaoNotas extends javax.swing.JPanel {

    private static int classe;
    
    public InsercaoNotas() {
        initComponents();
    }
    public DefaultTableModel getModelo()
    {
        return (DefaultTableModel)tblNotasInserir.getModel();
    }
    public static int getClasse() {
        return classe;
    }

    public static void setClasse(int classe) {
        InsercaoNotas.classe = classe;
    }
    
    public void preencher()
    {
        PreencheTabela preencher = new PreencheTabela(getClasse(),tblNotasInserir);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblNotasInserir = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setOpaque(false);

        tblNotasInserir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RA", "Nome do Aluno", "Nota "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblNotasInserir);
        if (tblNotasInserir.getColumnModel().getColumnCount() > 0) {
            tblNotasInserir.getColumnModel().getColumn(0).setMinWidth(150);
            tblNotasInserir.getColumnModel().getColumn(0).setPreferredWidth(150);
            tblNotasInserir.getColumnModel().getColumn(0).setMaxWidth(150);
            tblNotasInserir.getColumnModel().getColumn(1).setResizable(false);
            tblNotasInserir.getColumnModel().getColumn(2).setMinWidth(30);
            tblNotasInserir.getColumnModel().getColumn(2).setPreferredWidth(60);
            tblNotasInserir.getColumnModel().getColumn(2).setMaxWidth(60);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblNotasInserir;
    // End of variables declaration//GEN-END:variables
}
