/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.diretor;

import control.connection.dataAccess.AlunoAccess;
import control.graficos.BarraDeProgresso;
import control.connection.dataAccess.CategoriaAccess;
import control.connection.dataAccess.CidadeAccess;
import control.connection.dataAccess.EstadoAccess;
import control.connection.dataAccess.ProfessorAccess;
import control.connection.dataAccess.UsuarioAccess;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.border.Border;
import model.Aluno;
import model.CategoriaUsuario;
import model.Cidade;
import model.Estado;
import model.Professor;
import model.Usuario;

/**
 *
 * @author Aluno
 */
public class VisualizacaoDeIntegrantes extends javax.swing.JFrame {

   BarraDeProgresso bar = new BarraDeProgresso();
   private static CategoriaAccess acessoCte = new CategoriaAccess();
    private Usuario usuarioEsq;
    private EstadoAccess acessoEst = new EstadoAccess();
    private CidadeAccess acessoCid = new CidadeAccess();
   private static UsuarioAccess diretorAcesso = new UsuarioAccess();
   
    public VisualizacaoDeIntegrantes() {
        initComponents();
        this.setLocationRelativeTo(null);
      
        jComboBox2.setVisible(true);
        jButton2.setVisible(true);
       jlNome.setVisible(false);
       jlSobrenome.setVisible(false);
       jlEmail.setVisible(false);
       jLabelBairro.setVisible(false);
        jLabelData.setVisible(false);
        jLabel2.setVisible(false);
        jlNome.setVisible(false);
        jLabel8.setVisible(false);
        jLabelData1.setVisible(false);
        jlTXTdata.setVisible(false);
        jLabelData.setVisible(false);
        jlTXTcpf.setVisible(false);
        jLabel13.setVisible(false);
        jLabel12.setVisible(false);
       jLabelBairro.setVisible(false);
       JLBairroTXT.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jlNome = new javax.swing.JLabel();
        jlSobrenome = new javax.swing.JLabel();
        jlEmail = new javax.swing.JLabel();
        JLNomeTXT = new javax.swing.JLabel();
        JLSobrenomeTXT = new javax.swing.JLabel();
        JLEmailTXT = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelBairro = new javax.swing.JLabel();
        jLabelData = new javax.swing.JLabel();
        JLCidadeTXT = new javax.swing.JLabel();
        JLBairroTXT = new javax.swing.JLabel();
        JLGeneroTXT = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jlTXTcpf = new javax.swing.JLabel();
        jLabelData1 = new javax.swing.JLabel();
        jlTXTdata = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        JLEstadoTXT1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        imgPerfil = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1173, 730));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1173, 730));
        jPanel1.setMinimumSize(new java.awt.Dimension(1173, 730));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("DADOS DE ALUNOS E PROFESSORES");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(80, 380, 251, 30);

        jlNome.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jlNome.setForeground(new java.awt.Color(0, 77, 133));
        jlNome.setText("NOME:");
        jPanel3.add(jlNome);
        jlNome.setBounds(20, 140, 78, 19);

        jlSobrenome.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jlSobrenome.setForeground(new java.awt.Color(0, 77, 133));
        jlSobrenome.setText("SOBRENOME:");
        jPanel3.add(jlSobrenome);
        jlSobrenome.setBounds(20, 170, 90, 19);

        jlEmail.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jlEmail.setForeground(new java.awt.Color(0, 77, 133));
        jlEmail.setText("EMAIL:");
        jPanel3.add(jlEmail);
        jlEmail.setBounds(20, 200, 78, 19);

        JLNomeTXT.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        JLNomeTXT.setForeground(new java.awt.Color(0, 77, 133));
        jPanel3.add(JLNomeTXT);
        JLNomeTXT.setBounds(260, 130, 140, 30);

        JLSobrenomeTXT.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        JLSobrenomeTXT.setForeground(new java.awt.Color(0, 77, 133));
        jPanel3.add(JLSobrenomeTXT);
        JLSobrenomeTXT.setBounds(260, 160, 140, 30);

        JLEmailTXT.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        JLEmailTXT.setForeground(new java.awt.Color(0, 77, 133));
        jPanel3.add(JLEmailTXT);
        JLEmailTXT.setBounds(260, 190, 140, 30);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("SELECIONE OS CAMPOS AO LADO PARA VISUALIZAR ");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(30, 370, 350, 19);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 77, 133));
        jLabel2.setText("CIDADE:");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(20, 230, 70, 19);

        jLabelBairro.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelBairro.setForeground(new java.awt.Color(0, 77, 133));
        jLabelBairro.setText("BAIRRO:");
        jPanel3.add(jLabelBairro);
        jLabelBairro.setBounds(20, 300, 60, 19);

        jLabelData.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelData.setForeground(new java.awt.Color(0, 77, 133));
        jLabelData.setText("CPF:");
        jPanel3.add(jLabelData);
        jLabelData.setBounds(20, 390, 160, 20);

        JLCidadeTXT.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        JLCidadeTXT.setForeground(new java.awt.Color(0, 77, 133));
        JLCidadeTXT.setMaximumSize(new java.awt.Dimension(40, 14));
        JLCidadeTXT.setMinimumSize(new java.awt.Dimension(40, 14));
        JLCidadeTXT.setPreferredSize(new java.awt.Dimension(40, 14));
        jPanel3.add(JLCidadeTXT);
        JLCidadeTXT.setBounds(260, 220, 140, 30);

        JLBairroTXT.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        JLBairroTXT.setForeground(new java.awt.Color(0, 77, 133));
        jPanel3.add(JLBairroTXT);
        JLBairroTXT.setBounds(260, 290, 140, 30);

        JLGeneroTXT.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        JLGeneroTXT.setForeground(new java.awt.Color(0, 77, 133));
        jPanel3.add(JLGeneroTXT);
        JLGeneroTXT.setBounds(260, 320, 140, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/user_1.png"))); // NOI18N
        jPanel3.add(jLabel8);
        jLabel8.setBounds(150, 10, 64, 90);

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 77, 133));
        jLabel13.setText("GÊNERO:");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(20, 330, 70, 19);

        jlTXTcpf.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jlTXTcpf.setForeground(new java.awt.Color(0, 77, 133));
        jPanel3.add(jlTXTcpf);
        jlTXTcpf.setBounds(260, 380, 140, 30);

        jLabelData1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelData1.setForeground(new java.awt.Color(0, 77, 133));
        jLabelData1.setText("DATA DE NASCIMENTO:");
        jPanel3.add(jLabelData1);
        jLabelData1.setBounds(20, 360, 160, 20);

        jlTXTdata.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jlTXTdata.setForeground(new java.awt.Color(0, 77, 133));
        jPanel3.add(jlTXTdata);
        jlTXTdata.setBounds(260, 350, 140, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/diretor/learning(1).png"))); // NOI18N
        jPanel3.add(jLabel4);
        jLabel4.setBounds(80, 120, 266, 234);

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 77, 133));
        jLabel12.setText("ESTADO:");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(20, 260, 60, 19);

        JLEstadoTXT1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        JLEstadoTXT1.setForeground(new java.awt.Color(0, 77, 133));
        jPanel3.add(JLEstadoTXT1);
        JLEstadoTXT1.setBounds(260, 250, 140, 30);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(200, 100, 490, 510);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(290, 0, 890, 730);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/back-left-arrow-square-button-outline.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 10, 70, 40);

        imgPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/user-previa.png"))); // NOI18N
        jPanel1.add(imgPerfil);
        imgPerfil.setBounds(80, 90, 130, 150);

        lblNome.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblNome.setForeground(new java.awt.Color(255, 255, 255));
        lblNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNome.setText("Nome do Usuário");
        jPanel1.add(lblNome);
        lblNome.setBounds(30, 250, 220, 23);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PESSOAS DISPONÍVEIS");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 330, 140, 16);

        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        jComboBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBox2MousePressed(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(40, 370, 220, 30);

        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("BUSCAR");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButton2.setContentAreaFilled(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(40, 510, 220, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/bg-img.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(1173, 730));
        jLabel1.setMinimumSize(new java.awt.Dimension(1173, 730));
        jLabel1.setPreferredSize(new java.awt.Dimension(1173, 730));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1173, 730);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1173, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
       jLabel4.setVisible(false);
       jLabel6.setVisible(false);
       jlNome.setVisible(true);
       jlSobrenome.setVisible(true);
       jLabelBairro.setVisible(true);
      jLabelData.setVisible(true);
       jlEmail.setVisible(true);
       jLabel13.setVisible(true);
       JLSobrenomeTXT.setVisible(true);
       jLabel12.setVisible(true);
       JLEmailTXT.setVisible(true);
       JLNomeTXT.setVisible(true);
       jLabelBairro.setVisible(true);
       JLBairroTXT.setVisible(true);
       JLSobrenomeTXT.setText(usuarioEsq.getSobrenome());
       JLEmailTXT.setText(usuarioEsq.getEmail());
       JLNomeTXT.setText(usuarioEsq.getNome());
       jlTXTdata.setText(usuarioEsq.getDataNasc());
       jlTXTcpf.setText(usuarioEsq.getCPF());
       JLBairroTXT.setText(usuarioEsq.getBairro());
       jLabelData1.setVisible(true);
        jlTXTdata.setVisible(true);
        jLabelData.setVisible(true);
        jlTXTcpf.setVisible(true);
       jLabelBairro.setVisible(true);
       jLabel2.setVisible(true);
       jLabel8.setVisible(true);
       jLabel7.setVisible(false);
       Estado estado = acessoEst.read(usuarioEsq.getEstado());
       JLEstadoTXT1.setText(estado.getNome());
       Cidade cidade = acessoCid.read(usuarioEsq.getEstado(), usuarioEsq.getCidade());
       JLCidadeTXT.setText(cidade.getNome());
       if(usuarioEsq.getGenero()==null)
        JLGeneroTXT.setText("indefinido");
       
      
        

       
    }//GEN-LAST:event_jButton2MousePressed

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
       int id = jComboBox2.getSelectedIndex()+1;
       usuarioEsq = diretorAcesso.read(id);
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
      this.dispose();
    }//GEN-LAST:event_jLabel5MousePressed

    private void jComboBox2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MousePressed
        for(String usuario :diretorAcesso.lista())
        {
            jComboBox2.addItem(usuario);
        }  
    }//GEN-LAST:event_jComboBox2MousePressed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualizacaoDeIntegrantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualizacaoDeIntegrantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualizacaoDeIntegrantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualizacaoDeIntegrantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisualizacaoDeIntegrantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLBairroTXT;
    private javax.swing.JLabel JLCidadeTXT;
    private javax.swing.JLabel JLEmailTXT;
    private javax.swing.JLabel JLEstadoTXT1;
    private javax.swing.JLabel JLGeneroTXT;
    private javax.swing.JLabel JLNomeTXT;
    private javax.swing.JLabel JLSobrenomeTXT;
    private javax.swing.JLabel imgPerfil;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelData1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlSobrenome;
    private javax.swing.JLabel jlTXTcpf;
    private javax.swing.JLabel jlTXTdata;
    private javax.swing.JLabel lblNome;
    // End of variables declaration//GEN-END:variables
}
